### ISSUE TITLE
adjust pipeline to use valid selenoid url

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/pipeline-ce#188]
default example of the selenium url:
`selenium_url=http://demo:demo@hostname:443/selenoid/wd/hub`

1. there is no need anymore `demo:demo` credentials
2. for secured env we have to use automatically `https`

**Comment by vdelendik** [comment]
let's investigate possibility to reuse attached to the folder or global `config.properties` with default settings aka embedded selenoid/mcloud and maybe browserstack/saucelab/testingbot so every admin could enable integration via this config.properties attached to the org folder. That's might be effective integrations replacement for the Community Edition version where selenium hub providers were removed.

**Comment by vdelendik** [comment]
done. during the testing using `ZEBRUNNER_VERSION=develop` pipeline run web demo job.
1. selenium_url should be equal to `http://selenoid:4444/wd/hub`
2. web demo job executed as regular

**Comment by okamara** [comment]
Setup zebrunner from develop branch, still see old version of UR
<img width="928" alt="Снимок экрана 2021-12-03 в 13 36 00" src="https://user-images.githubusercontent.com/32964663/144588591-e2440bcc-0186-40bc-9f08-8f5b95e1f2c6.png">
L

**Comment by okamara** [comment]
Re-verified, fixed.
